# Generated by Django 6.0.6 on 2026-09-25 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Full analyzed target URL', max_length=2048)),
                ('domain', models.CharField(db_index=True, help_text='Extracted domain/host', max_length=255)),
                ('risk_score', models.IntegerField(help_text='Safety/Trustworthiness score (0 = Critical Risk, 100 = Low Risk/Safe)')),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='MEDIUM', help_text='Categorized risk tier: LOW, MEDIUM, HIGH, CRITICAL', max_length=20)),
                ('ssl_status', models.BooleanField(default=False, help_text='True if a valid and active SSL/TLS certificate was verified')),
                ('phishing_detected', models.BooleanField(default=False, help_text='True if deceptive credential/brand phishing patterns were detected')),
                ('malware_detected', models.BooleanField(default=False, help_text='True if malware distribution/exploit indicators were flagged')),
                ('suspicious_redirects', models.BooleanField(default=False, help_text='True if deceptive redirect chains or protocol downgrades were detected')),
                ('domain_age', models.CharField(default='Unknown', help_text="Domain age derived from registration records (e.g. '8 months', '2 years')", max_length=100)),
                ('content_analysis', models.JSONField(blank=True, default=dict, help_text='Structured breakdown of DOM inspection, forms, tokens, and AI insights')),
                ('security_summary', models.TextField(blank=True, help_text='Synthesized summary of security findings and caution advice')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the scan was executed')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the scan, or null for public/guest scans.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Scan',
                'verbose_name_plural': 'Website Scans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='scan_user_created_idx'), models.Index(fields=['domain'], name='scan_domain_idx'), models.Index(fields=['created_at'], name='scan_created_idx')],
            },
        ),
    ]
